name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp://disnetdev.co.za
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /disnetdev.co.za/public_html/
